import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import versionJson from './version.json'

// version.json is the source of truth for the game version; the backend keeps
// a copy at backend/version.json, regenerated by scripts/version_sync.py (the
// two deploy separately, so neither can read one shared file at runtime).
// Inlined into the bundle at build time as __GAME_VERSION__ rather than
// fetched, so what the menu shows can't drift from the build it shipped with.
// A committed file rather than .env: .env is gitignored here, so a version
// read from one would vanish on a fresh clone or a build host.
const version = versionJson.version

export default defineConfig(({ mode }) => {
  // '' prefix loads every var, not just VITE_*. API_TARGET is only used by
  // the dev server here and never reaches the browser bundle. A shell var
  // (API_TARGET=... npm run dev) overrides frontend/.env.
  const env = loadEnv(mode, '.', '')

  return {
    plugins: [react()],
    define: {
      __GAME_VERSION__: JSON.stringify(version)
    },
    server: {
      port: 3000,
      host: true,
      proxy: {
        '/api': {
          target: env.API_TARGET || 'http://127.0.0.1:8000',
          changeOrigin: true
        }
      }
    }
  }
})
